let adviseesJustinJSONarray = [
    {
        "lName": "Al Shorman",
        "fName": "Deef Allah",
        "mName": "M Y",
        "NUID": 46892717,
        "Email": "dalshorman2@huskers.unl.edu",
        "portfolioURL": "https://www.linkedin.com/in/deef-allah-al-shorman-82b386207/",
        "US": "Non-US",
        "Citizen": "JOR",
        "prog_status": "Active",
        "current": "coursework",
        "admitted": 1218,
        "degree": "D",
        "primary_plan": "EDUS-PHD (INLT-SPC)",
        "minor": "",
        "first_grad_enrolled": 1201,
        "lastest_enrolled": 1228,
        "latest_grad_eligible": 1228,
        "gs_holds": "",
        "dept_funding": "$16,000 GA, $1,500 Fellowships",
        "advisor": "Justin D Olmanson",
        "committee_members_doc": "Al Steckelberg, June Griffin, Guy Trainin",
        "PoS": "2022/05/04",
        "candidacy": "",
        "examForm": "",
        "diss_deposited": "",
        "expiration": "2028/05/01",
        "cr_hrs_taken": 66,
        "courses_taken": "TEAC 800, TEAC 882B, TEAC 882D, TEAC 801, TEAC 880A, TEAC 880P, TEAC 859, TEAC 860, ENTO 830, TEAC 889, TEAC 959, TEAC 960, EDPS 800, EDPS 859, TEAC 995A, EDPS 870, EDPS 941, TEAC 880E, TEAC 895, TEAC 999, EDPS 942, TEAC 905, TEAC 995",
        "imageFile": "deef.jpg",
        "imageURL": ""
    },
    {
        "lName": "Falls",
        "fName": "Zoe",
        "mName": "",
        "NUID": 45892717,
        "Email": "zoe.falls@gmail.com",
        "portfolioURL": "https://www.linkedin.com/in/zfalls/",
        "US": "US Citizen",
        "Citizen": "",
        "prog_status": "Active",
        "current": "graduation",
        "admitted": 1151,
        "degree": "D",
        "primary_plan": "EDUS-PHD (INLT-SPC)",
        "minor": "",
        "first_grad_enrolled": 1151,
        "lastest_enrolled": 1201,
        "latest_grad_eligible": 1201,
        "gs_holds": "",
        "dept_funding": "$16,000 GA, $1,500 Fellowships",
        "advisor": "Justin D Olmanson",
        "committee_members_doc": "STEM Faculty, Loukia Sarroub, Guy Trainin",
        "PoS": "2017/04/04",
        "candidacy": "2017/04/04",
        "examForm": "2020/04/04",
        "diss_deposited": "2020/05/04",
        "expiration": "2023/05/01",
        "cr_hrs_taken": 99,
        "courses_taken": "TEAC 800, TEAC 882B, TEAC 882D, TEAC 801, TEAC 880A, TEAC 880P, TEAC 859, TEAC 860, ENTO 830, TEAC 889, TEAC 959, TEAC 960, EDPS 800, EDPS 859, TEAC 995A, EDPS 870, EDPS 941, TEAC 880E, TEAC 895, TEAC 999, EDPS 942, TEAC 905, TEAC 995",
        "imageFile": "zoe.jpg",
        "imageURL": ""
    },
    {
        "lName": "Binkley",
        "fName": "Shannon",
        "mName": "Rochelle",
        "NUID": 77433047,
        "Email": "sbottom@lps.org",
        "portfolioURL": "https://www.linkedin.com/in/shannon-binkley/",
        "US": "US Citizen",
        "Citizen": "",
        "prog_status": "Active",
        "current": "coursework",
        "admitted": 1225,
        "degree": "M",
        "primary_plan": "TEAC-MA (INLT-SPC)",
        "minor": "",
        "first_grad_enrolled": 1015,
        "lastest_enrolled": 1228,
        "latest_grad_eligible": 1228,
        "gs_holds": "",
        "dept_funding": "",
        "advisor": "Justin D Olmanson",
        "committee_members_doc": "",
        "PoS": "",
        "candidacy": "",
        "examForm": "",
        "diss_deposited": "",
        "expiration": "2030/08/01",
        "cr_hrs_taken": 22,
        "courses_taken": "GEOS 898, SOCI 898, TEAC 893, CSCE 805T, TEAC 851L, TEAC 880A ",
        "imageFile": "shannon.jpg",
        "imageURL": ""
    },
    {
        "lName": "Bishop",
        "fName": "Susanne",
        "mName": "M",
        "NUID": 37378095,
        "Email": "susanne.bishop@unmc.edu",
        "portfolioURL": "https://www.linkedin.com/in/susanne-bishop-3a37b923/",
        "US": "US Citizen",
        "Citizen": "",
        "prog_status": "Active",
        "current": "coursework",
        "admitted": 1218,
        "degree": "M",
        "primary_plan": "TEAC-MA (INLT-SPC)",
        "minor": "",
        "first_grad_enrolled": 1218,
        "lastest_enrolled": 1228,
        "latest_grad_eligible": 1228,
        "gs_holds": "",
        "dept_funding": "",
        "advisor": "Justin D Olmanson",
        "committee_members_doc": "",
        "PoS": "",
        "candidacy": "",
        "examForm": "",
        "diss_deposited": "",
        "expiration": "2029/12/31",
        "cr_hrs_taken": 6,
        "courses_taken": "TEAC 800, TEAC  801 ",
        "imageFile": "susanne.jpg",
        "imageURL": ""
    },
    {
        "lName": "Choat",
        "fName": "Adina",
        "mName": "M",
        "NUID": 47826479,
        "Email": "adinamarie@huskers.unl.edu",
        "portfolioURL": "https://www.linkedin.com/in/adina-choat-8b1074a0/",
        "US": "US Citizen",
        "Citizen": "",
        "prog_status": "Active",
        "current": "coursework",
        "admitted": 1208,
        "degree": "M",
        "primary_plan": "TEAC-MA",
        "minor": "",
        "first_grad_enrolled": 1101,
        "lastest_enrolled": 1218,
        "latest_grad_eligible": 1228,
        "gs_holds": "",
        "dept_funding": "",
        "advisor": "Justin D Olmanson",
        "committee_members_doc": "",
        "PoS": "",
        "candidacy": "",
        "examForm": "",
        "diss_deposited": "",
        "expiration": "2028/12/31",
        "cr_hrs_taken": 62,
        "courses_taken": "ACCT 804, ACCT 819, TEAC 860, TEAC 880A, TEAC 882B, TEAC 800, TEAC 801, TEAC 861 ",
        "imageFile": "adina.jpg",
        "imageURL": ""
    },
    {
        "lName": "Eno",
        "fName": "Alan",
        "mName": "",
        "NUID": 38535314,
        "Email": "alaneno@unl.edu",
        "portfolioURL": "https://www.linkedin.com/in/alaneno/",
        "US": "US Citizen",
        "Citizen": "",
        "prog_status": "Active",
        "current": "comps",
        "admitted": 1141,
        "degree": "D",
        "primary_plan": "EDUS-PHD (INLT-SPC)",
        "minor": "",
        "first_grad_enrolled": 1088,
        "lastest_enrolled": 1221,
        "latest_grad_eligible": 1228,
        "gs_holds": "",
        "dept_funding": "",
        "advisor": "Justin D Olmanson",
        "committee_members_doc": "Guy Trainin, Al Steckelberg, Adam Wagler",
        "PoS": "2014/03/19",
        "candidacy": "",
        "examForm": "",
        "diss_deposited": "",
        "expiration": "2023/05/01",
        "cr_hrs_taken": 94,
        "courses_taken": "EDPS 854, TEAC 995A, EDPS 859, EDPS 900K, EDPS 960, EDPS 870, EDPS 800, TEAC 995, EDPS 921, TEAC 849A, EDPS 900B, TEAC 860, TEAC 882B, TEAC 995, TEAC 859, EDPS 935, EDPS 936, EDPS 941, TEAC 995, TEAC 996",
        "imageFile": "alan.jpg",
        "imageURL": ""
    },
    {
        "lName": "Even",
        "fName": "Tuggen",
        "mName": "",
        "NUID": 42377399,
        "Email": "tuggeneven@outlook.com",
        "portfolioURL": "https://www.linkedin.com/in/tuggen-even-msed-599205a4/",
        "US": "Non-US",
        "Citizen": "TUR",
        "prog_status": "Active",
        "admitted": 1218,
        "current": "PoS",
        "degree": "D",
        "primary_plan": "EDUS-PHD (INLT-SPC)",
        "minor": "",
        "first_grad_enrolled": 1218,
        "lastest_enrolled": 1225,
        "latest_grad_eligible": 1228,
        "gs_holds": "",
        "dept_funding": "",
        "advisor": "Justin D Olmanson",
        "committee_members_doc": "",
        "PoS": "",
        "candidacy": "",
        "examForm": "",
        "diss_deposited": "",
        "expiration": "2030/12/31",
        "cr_hrs_taken": 12,
        "courses_taken": "TEAC 859, TEAC 995A, TEAC 882B, TEAC 858",
        "imageFile": "tuggen.jpg",
        "imageURL": ""
    },
    {
        "lName": "Hassani",
        "fName": "Azadeh",
        "mName": "",
        "NUID": 5441098,
        "Email": "a.hassani.tefl@gmail.com",
        "portfolioURL": "https://www.linkedin.com/in/tuggen-even-msed-599205a4/",
        "US": "Non-US",
        "Citizen": "IRN",
        "prog_status": "Active",
        "current": "admitted",
        "admitted": 1228,
        "degree": "D",
        "primary_plan": "EDUS-PHD (INLT-SPC)",
        "minor": "",
        "first_grad_enrolled": null,
        "lastest_enrolled": null,
        "latest_grad_eligible": 1228,
        "gs_holds": "Engl Test 1228-1228 (2022-10-01). Trnscrpt 1228-1238 (2022-10-01).",
        "dept_funding": "",
        "advisor": "Justin D Olmanson",
        "committee_members_doc": "",
        "PoS": "",
        "candidacy": "",
        "examForm": "",
        "diss_deposited": "",
        "expiration": "2030/12/31",
        "cr_hrs_taken": 0,
        "courses_taken": "",
        "imageFile": "azadeh.jpg",
        "imageURL": ""
    },
    {
        "lName": "Headley",
        "fName": "Sam",
        "mName": "",
        "NUID": 60113197,
        "Email": "SHEADLEY2@UNL.EDU",
        "portfolioURL": "https://www.linkedin.com/in/samantha-headley-224583165/",
        "US": "US Citizen",
        "Citizen": "",
        "prog_status": "Active",
        "current": "admitted",
        "admitted": 1225,
        "degree": "M",
        "primary_plan": "TEAC-MA (INLT-SPC)",
        "minor": "",
        "first_grad_enrolled": 1198,
        "lastest_enrolled": 1228,
        "latest_grad_eligible": 1228,
        "gs_holds": "",
        "dept_funding": "",
        "advisor": "Justin D Olmanson",
        "committee_members_doc": "",
        "PoS": "",
        "candidacy": "",
        "examForm": "",
        "diss_deposited": "",
        "expiration": "2030/08/01",
        "cr_hrs_taken": 15,
        "courses_taken": "ADPR 830, ADPR 866, ADPR 834, ADPR 850, TEAC 800 ",
        "imageFile": "sam.jpg",
        "imageURL": ""
    },
    {
        "lName": "Jorgenson",
        "fName": "Brevan",
        "mName": "",
        "NUID": 12722829,
        "Email": "bjorgenson@nebraska.edu",
        "portfolioURL": "https://www.linkedin.com/in/brevan-jorgenson/",
        "US": "US Citizen",
        "Citizen": "",
        "prog_status": "Active",
        "current": "PoS",
        "admitted": 1218,
        "degree": "D",
        "primary_plan": "EDUS-PHD (INLT-SPC)",
        "minor": "",
        "first_grad_enrolled": 1218,
        "lastest_enrolled": 1228,
        "latest_grad_eligible": 1228,
        "gs_holds": "",
        "dept_funding": "",
        "advisor": "Justin D Olmanson",
        "committee_members_doc": "",
        "PoS": "",
        "candidacy": "",
        "examForm": "",
        "diss_deposited": "",
        "expiration": "2029/12/31",
        "cr_hrs_taken": 15,
        "courses_taken": "TEAC 895, TEAC 995A, TEAC 880E, TEAC 882B, TEAC 858 ",
        "imageFile": "brevan.jpg",
        "imageURL": ""
    },
    {
        "lName": "Julian",
        "fName": "Terry",
        "mName": "",
        "NUID": 43101524,
        "Email": "terry.julian@hpstigers.org",
        "portfolioURL": "https://www.linkedin.com/in/terry-julian-6b17716b/",
        "US": "US Citizen",
        "Citizen": "",
        "prog_status": "Active",
        "current": "coursework",
        "admitted": 1205,
        "degree": "M",
        "primary_plan": "TEAC-MA",
        "minor": "",
        "first_grad_enrolled": 1205,
        "lastest_enrolled": 1215,
        "latest_grad_eligible": 1228,
        "gs_holds": "",
        "dept_funding": "",
        "advisor": "Justin D Olmanson",
        "committee_members_doc": "",
        "PoS": "",
        "candidacy": "",
        "examForm": "",
        "diss_deposited": "",
        "expiration": "2028/08/01",
        "cr_hrs_taken": 9,
        "courses_taken": "CSCE 805T, TEAC 851L, TEAC 890 ",
        "imageFile": "terry.jpg",
        "imageURL": ""
    },
    {
        "lName": "Kabir",
        "fName": "Tamanna Sharmin",
        "mName": "",
        "NUID": 98428166,
        "Email": "lianatsk@gmail.com",
        "portfolioURL": "https://www.linkedin.com/in/tamanna-kabir-679aa421a/",
        "US": "Non-US",
        "Citizen": "BGD",
        "prog_status": "Active",
        "current": "PoS",
        "admitted": 1218,
        "degree": "D",
        "primary_plan": "EDUS-PHD (INLT-SPC)",
        "minor": "TESO-GCER (certificate, not minor)",
        "first_grad_enrolled": 1218,
        "lastest_enrolled": 1225,
        "latest_grad_eligible": 1228,
        "gs_holds": "",
        "dept_funding": "$14,500 GA, $3,920 Fellowships",
        "advisor": "Justin D Olmanson",
        "committee_members_doc": "",
        "PoS": "",
        "candidacy": "",
        "examForm": "",
        "diss_deposited": "",
        "expiration": "2029/12/31",
        "cr_hrs_taken": 18,
        "courses_taken": "TEAC 838, TEAC 859, TEAC 995A, EDPS 900K, TEAC 813P, TEAC 882B ",
        "imageFile": "tamanna.jpg",
        "imageURL": ""
    },
    {
        "lName": "Kelsey",
        "fName": "Mackayla",
        "mName": "A L",
        "NUID": 55950309,
        "Email": "mackayla.kelsey@huskers.unl.edu",
        "portfolioURL": "https://www.linkedin.com/in/mackayla-kelsey-892187ba/",
        "US": "US Citizen",
        "Citizen": "",
        "prog_status": "Active",
        "current": "PoS",
        "admitted": 1218,
        "degree": "D",
        "primary_plan": "EDUS-PHD (INLT-SPC)",
        "minor": "",
        "first_grad_enrolled": 1175,
        "lastest_enrolled": 1228,
        "latest_grad_eligible": 1228,
        "gs_holds": "",
        "dept_funding": "$14,500 GA, $7,500 Fellowships",
        "advisor": "Justin D Olmanson",
        "committee_members_doc": "",
        "PoS": "",
        "candidacy": "",
        "examForm": "",
        "diss_deposited": "",
        "expiration": "2029/12/31",
        "cr_hrs_taken": 18,
        "courses_taken": "",
        "imageFile": "mackayla.jpg",
        "imageURL": ""
    },
    {
        "lName": "Khandan",
        "fName": "Farnoosh",
        "mName": "",
        "NUID": 97118638,
        "Email": "farnooshkhandan87@gmail.com",
        "portfolioURL": "https://www.linkedin.com/in/farnoosh-khandan-69987b247/",
        "US": "Non-US",
        "Citizen": "IRN",
        "prog_status": "Active",
        "current": "coursework",
        "admitted": 1225,
        "degree": "D",
        "primary_plan": "EDUS-PHD (INLT-SPC)",
        "minor": "",
        "first_grad_enrolled": 1225,
        "lastest_enrolled": 1228,
        "latest_grad_eligible": 1228,
        "gs_holds": "Engl Test 1228-1228 (2022-10-01).",
        "dept_funding": "$17,345 GA",
        "advisor": "Justin D Olmanson",
        "committee_members_doc": "",
        "PoS": "",
        "candidacy": "",
        "examForm": "",
        "diss_deposited": "",
        "expiration": "2030/12/31",
        "cr_hrs_taken": 6,
        "courses_taken": "EDPS 854, EDPS 900K ",
        "imageFile": "farnoosh.jpg",
        "imageURL": ""
    },
    {
        "lName": "Larsen",
        "fName": "Gretchen",
        "mName": "Kathleen",
        "NUID": 56689944,
        "Email": "glarsen@huskers.unl.edu",
        "portfolioURL": "http://gretch.in/",
        "US": "US Citizen",
        "Citizen": "",
        "prog_status": "Active",
        "current": "proposal",
        "admitted": 1185,
        "degree": "D",
        "primary_plan": "EDUS-PHD (INLT-SPC)",
        "minor": "",
        "first_grad_enrolled": 1141,
        "lastest_enrolled": 1228,
        "latest_grad_eligible": 1228,
        "gs_holds": "",
        "dept_funding": "$14,500 GA, $3,500 Fellowship",
        "advisor": "Justin D Olmanson",
        "committee_members_doc": "Guy Trainin, Amanda Morales, Santiago Cal",
        "PoS": "",
        "candidacy": "",
        "examForm": "",
        "diss_deposited": "",
        "expiration": "2026/05/01",
        "cr_hrs_taken": 94,
        "courses_taken": "SCLP 811, TEAC 859, TEAC 995A, SCLP 896, TEAC 882B, TEAC 882D, ARTP 896, ARCH 826, SCLP 812, TEAC 949, ARTP 896, TEAC 895, TEAC 930A, TEAC 895, TEAC 930B, TEAC 995, AHIS 898, ARTP 997, SCLP 911, AHIS 846, SCLP 912, TEAC 996, AHIS 911, TEAC 996 ",
        "imageFile": "gretchen.jpg",
        "imageURL": ""
    },
    {
        "lName": "Mason-D'Croz",
        "fName": "Michael",
        "mName": "Andrew",
        "NUID": 18328619,
        "Email": "mmasondcroz@gmail.com",
        "portfolioURL": "https://www.linkedin.com/in/michael-mason-d-croz-2a3b9b27/",
        "US": "US Citizen",
        "Citizen": "",
        "prog_status": "Active",
        "current": "comps",
        "admitted": 1211,
        "degree": "D",
        "primary_plan": "EDUS-EDD (INLT-SPC)",
        "minor": "",
        "first_grad_enrolled": 1091,
        "lastest_enrolled": 1228,
        "latest_grad_eligible": 1228,
        "gs_holds": "",
        "dept_funding": "",
        "advisor": "Justin D Olmanson",
        "committee_members_doc": "Ali Moeller, Jenelle Reeves, Robert Twomey",
        "PoS": "",
        "candidacy": "",
        "examForm": "",
        "diss_deposited": "",
        "expiration": "2029/12/31",
        "cr_hrs_taken": 79,
        "courses_taken": "TEAC 889, TEAC 895, TEAC 922O, TEAC 882D, TEAC 995, TEAC 880M, TEAC 930B, TEAC 995, TEAC 859, TEAC 860, TEAC 995B, TEAC 930K, TEAC 858, TEAC 862, TEAC 949 ",
        "imageFile": "michael.jpg",
        "imageURL": ""
    },
    {
        "lName": "Palala Martinez",
        "fName": "Hector",
        "mName": "de Jesus",
        "NUID": 88037789,
        "Email": "hectorpalala@huskers.unl.edu",
        "portfolioURL": "https://www.linkedin.com/in/hectorpalala/",
        "US": "Non-US",
        "Citizen": "GTM",
        "prog_status": "Active",
        "current": "comps",
        "admitted": 1198,
        "degree": "D",
        "primary_plan": "EDUS-PHD (INLT-SPC)",
        "minor": "",
        "first_grad_enrolled": 1178,
        "lastest_enrolled": 1221,
        "latest_grad_eligible": 1228,
        "gs_holds": "",
        "dept_funding": "$14,500 GA, $1,225 Fellowships",
        "advisor": "Justin D Olmanson, Ted Hamann",
        "committee_members_doc": "Theresa Catalano, Amanda Morales, Isabel Velazquez",
        "PoS": "2021/06/09",
        "candidacy": "",
        "examForm": "",
        "diss_deposited": "",
        "expiration": "2027/08/01",
        "cr_hrs_taken": 96,
        "courses_taken": "ENGL 887, TEAC 859, TEAC 860, TEAC 880A, TEAC 831A, TEAC 882B, TEAC 882D, TEAC 996, TEAC 800, TEAC 861, TEAC 936, TEAC 801, TEAC 899, TEAC 840E, TEAC 949, TEAC 995A, SPAN 891, TEAC 851R, TEAC 944B, SPAN 888, TEAC 805, TEAC 831J, TEAC 930B,  TEAC 815A, TEAC 960, EDPS 900K, TEAC 813K, TEAC 948, EDPS 936, TEAC 996",
        "imageFile": "hector.jpg",
        "imageURL": ""
    },
    {
        "lName": "Patrick",
        "fName": "Ryan",
        "mName": "Stewart",
        "NUID": 40047896,
        "Email": "rpatrick5@huskers.unl.edu",
        "portfolioURL": "https://www.linkedin.com/in/ryan-patrick-64a3995a/",
        "US": "US Citizen",
        "Citizen": "",
        "prog_status": "Active",
        "current": "comps",
        "admitted": 1161,
        "degree": "D",
        "primary_plan": "EDUS-PHD (INST-SPC)",
        "minor": "",
        "first_grad_enrolled": 1161,
        "lastest_enrolled": 1225,
        "latest_grad_eligible": 1228,
        "gs_holds": "",
        "dept_funding": "",
        "advisor": "Justin D Olmanson",
        "committee_members_doc": "Al Steckelberg, Guy Trainin, Stephen Cooper",
        "PoS": "2016/12/06",
        "candidacy": "",
        "examForm": "",
        "diss_deposited": "",
        "expiration": "2024/12/01",
        "cr_hrs_taken": 67,
        "courses_taken": "TEAC 882J, EDPS 854, EDPS 859, TEAC 995A, EDPS 800, EDPS 966, TEAC 995, TEAC 936, EDPS 941, TEAC 930A, EDPS 967, EDPS 972, ALEC 830, TEAC 805, TEAC 860, TEAC 882B, EDPS 942, TEAC 859, TEAC 960",
        "imageFile": "ryan.jpg",
        "imageURL": ""
    },
    {
        "lName": "Pilakowski",
        "fName": "Melissa",
        "mName": "Sue",
        "NUID": 74733267,
        "Email": "mpilakowski3@huskers.unl.edu",
        "portfolioURL": "https://www.linkedin.com/in/melissa-pilakowski-24a297aa/",
        "US": "US Citizen",
        "Citizen": "",
        "prog_status": "Active",
        "admitted": 1191,
        "degree": "D",
        "primary_plan": "EDUS-EDD (INST-SPC)",
        "minor": "",
        "first_grad_enrolled": 1191,
        "lastest_enrolled": 1221,
        "latest_grad_eligible": 1228,
        "gs_holds": "",
        "dept_funding": "",
        "advisor": "Justin D Olmanson",
        "committee_members_doc": "",
        "PoS": "",
        "candidacy": "",
        "examForm": "",
        "diss_deposited": "",
        "expiration": "2027/08/01",
        "cr_hrs_taken": 49,
        "courses_taken": "TEAC 949, TEAC 995, EDPS 855, TEAC 859, TEAC 930, TEAC 882D, TEAC 930, TEAC 854, TEAC 858, TEAC 930, TEAC 999, TEAC 957B ",
        "imageFile": "melissa.jpg",
        "imageURL": ""
    },
    {
        "lName": "Robbins",
        "fName": "Katherine",
        "mName": "M",
        "NUID": 51808797,
        "Email": "katierobbins7@gmail.com",
        "portfolioURL": "https://www.linkedin.com/in/katherinerobbins1/",
        "US": "US Citizen",
        "Citizen": "",
        "prog_status": "Active",
        "current": "dissertation",
        "admitted": 1131,
        "degree": "D",
        "primary_plan": "EDUS-PHD (INST-SPC)",
        "minor": "",
        "first_grad_enrolled": 1131,
        "lastest_enrolled": 1221,
        "latest_grad_eligible": 1228,
        "gs_holds": "",
        "dept_funding": "",
        "advisor": "Justin D Olmanson",
        "committee_members_doc": "Al Steckelberg, June Griffin, Guy Trainin",
        "PoS": "2014/01/08",
        "candidacy": "2015/04/01",
        "examForm": "",
        "diss_deposited": "",
        "expiration": "2021/12/01",
        "cr_hrs_taken": 87,
        "courses_taken": "TEAC 880A, TEAC 880P, EDPS 854, EDPS 859, TEAC 856A, TEAC 860, TEAC 995, ALEC 830, EDPS 860, ENGL 973, TEAC 882B, EDPS 900K, EDAD 988, EDPS 93, ENGL 878, TEAC 960, TEAC 999 ",
        "imageFile": "katherine.jpg",
        "imageURL": ""
    },
    {
        "lName": "Shcherbakov",
        "fName": "Ilia",
        "mName": "",
        "NUID": 94913775,
        "Email": "shcherbakov.eli@gmail.com",
        "portfolioURL": "https://www.linkedin.com/in/ilia-shcherbakov-685a68247/",
        "US": "Non-US",
        "Citizen": "RUS",
        "prog_status": "Active",
        "current": "admitted",
        "admitted": 1228,
        "degree": "D",
        "primary_plan": "EDUS-PHD (INLT-SPC)",
        "minor": "",
        "first_grad_enrolled": 1198,
        "lastest_enrolled": 1201,
        "latest_grad_eligible": 1228,
        "gs_holds": "",
        "dept_funding": "$16,816.67 GA, $4,000 Fellowship",
        "advisor": "Justin D Olmanson",
        "committee_members_doc": "",
        "PoS": "",
        "candidacy": "",
        "examForm": "",
        "diss_deposited": "",
        "expiration": "2030/12/31",
        "cr_hrs_taken": 9,
        "courses_taken": "MODL 880, TEAC 805, TEAC 851R,  ",
        "imageFile": "ilia.jpg",
        "imageURL": ""
    },
    {
        "lName": "Young",
        "fName": "Sarah",
        "mName": "Elizabeth",
        "NUID": 53892151,
        "Email": "sarahelizabeth.ne@gmail.com",
        "portfolioURL": "https://www.linkedin.com/in/sarah-beth-young-17714015b/",
        "US": "US Citizen",
        "Citizen": "",
        "prog_status": "Active",
        "current": "coursework",
        "admitted": 1211,
        "degree": "D",
        "primary_plan": "EDUS-EDD (INLT-SPC)",
        "minor": "",
        "first_grad_enrolled": 1101,
        "lastest_enrolled": 1225,
        "latest_grad_eligible": 1228,
        "gs_holds": "",
        "dept_funding": "",
        "advisor": "Justin D Olmanson",
        "committee_members_doc": "Jenelle Reeves, Stephanie Wessels, Stephen Ramsey",
        "PoS": "2022/01/12",
        "candidacy": "",
        "examForm": "",
        "diss_deposited": "",
        "expiration": "2030/05/01",
        "cr_hrs_taken": 72,
        "courses_taken": "TEAC 895, TEAC 889, TEAC 882D, TEAC 995, TEAC 880M, TEAC 930B, TEAC 859, TEAC 860, 995B, TEAC 908E, TEAC 930K, TEAC 858, TEAC 949",
        "imageFile": "sarah.jpg",
        "imageURL": ""
    }
]
